### ISSUE TITLE
License in branch v4 clarification

### ISSUE THREAD

**Issue by krtr** [lukasz-okuniewicz/custom-pixi-particles#1]
Hey,

First I would like to say, that your library is very impressive and brings much needed workflow and feature improvements to PIXI world, especially in combination with particle editor and I would love to use it in my commercial project.

But during due diligence I noticed that you changed licence in `v4` branch to GNU GPL v2.
The only thing that I would like to clarify is that it was intentional change and I should expect this licence in future releases of your awesome library.

**Comment by lukasz-okuniewicz** [comment]
Hi,

Thanks for the kind words about CustomPIXIParticles! I'm glad to hear it's bringing workflow improvements and strong features to your PIXI projects, especially alongside the particle editor.

You're correct – the license for the v4 branch and potentially future releases has indeed switched to GNU GPL v2. This change was intentional.

Here are some reasons behind the license switch:
**Foster a Collaborative Community**: I switched to GPLv2 to encourage a more collaborative open-source community around CustomPIXIParticles. This means developers can contribute improvements and bug fixes, benefiting everyone who uses the library.
**Long-Term Sustainability**: I believe the GPLv2 license will help ensure the long-term sustainability of CustomPIXIParticles by encouraging contributions and wider adoption, ultimately benefiting the entire developer community using PIXI.
**Maintain Open-Source Philosophy**: CustomPIXIParticles has always been built on the principles of open-source development. The GPLv2 license best reflects this philosophy and ensures the library remains freely available and modifiable for everyone.

I understand this might impact your commercial project's needs. If you have any questions about the implications of the GPLv2 license or would like to discuss alternative options, feel free to reach out directly.

Thanks again for your interest in CustomPIXIParticles!
