### ISSUE TITLE
spawnType FrameRectangle

### ISSUE THREAD

**Issue by talhaozdemir** [lukasz-okuniewicz/custom-pixi-particles#4]
First of all thanks for the plugin it is easy to implement and use, I want to use FrameRectangle prop but it is removed from the code and some particles are not able to downloaded like "sun". On the other hand it will be good if we can copy particle props instead of download them.

**Comment by talhaozdemir** [comment]
One other thing is, it would be good if unused props are not included in the downloaded file, for example if I don't use  warp so don't include them in the .json file

**Comment by lukasz-okuniewicz** [comment]
Hi there,

Thanks for reaching out and for the kind words about CustomPIXIParticles! I appreciate you bringing these points to my attention.

**FrameRectangle**
I'm happy to inform you that I've fixed the FrameRectangle prop.

**Particle Download**
While you can now download specific particle configurations directly, some example particles cannot be downloaded because they combine multiple emitters. These examples showcase achievable effects, not individual configurations.

**Unused Props in Downloaded Files**
Unused props are no longer included in the downloaded JSON files.

In the meantime, if you have any further questions or need clarification on anything, please don't hesitate to ask!

Thanks

**Comment by talhaozdemir** [comment]
Thanks for the quick response, I've just seen the plugin and I am trying it for a project.
