### ISSUE TITLE
Pixi-Spine support

### ISSUE THREAD

**Issue by wpitallo** [lukasz-okuniewicz/custom-pixi-particles#6]
Hi Just want to check if this supports Pixi-Spine, so can pixi-spine animations be emitted as particles?

**Comment by lukasz-okuniewicz** [comment]
Spine animations cannot be used with custom Pixi particles because they rely on PIXI.ParticleContainer. The PIXI.ParticleContainer is specifically optimized for rendering a large number of sprites by sharing the same base texture and supporting only limited transformations (position, scale, rotation, and alpha). However, it does not support complex display objects like Spine animations.
