### ISSUE TITLE
pixi.js-legacy should be moved to dependency (and removed from dev dependency)

### ISSUE THREAD

**Issue by AusPrinzip** [lukasz-okuniewicz/custom-pixi-particles#8]
I have noticed that from npm version 5.0.1 "pixi.js-legacy" is an actual dependency but in your package.json it shows as dev dependency.

As a worked around, i need to manually install pixi legacy for this library to work.

**Comment by lukasz-okuniewicz** [comment]
Hi @AusPrinzip,

Thank you for bringing this to my attention and for providing detailed feedback.

You are correct, pixi.js-legacy should be listed as a regular dependency in the package.json rather than a devDependency. Having it under devDependencies means it isn't automatically installed when someone installs your package, which leads to the issue you encountered.

I’m happy to inform you that in the latest version of `custom-pixi-particles`, pixi.js-legacy is correctly listed under the "dependencies" section in the package.json.

Thanks again for your help in improving the library!

Best regards,
Łukasz
